# Generated by Django 4.2.4 on 2024-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=300)),
                ('starting_date', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('industry', models.IntegerField(choices=[(1, 'ITES'), (2, 'Health Tech'), (3, 'AI'), (4, 'Ed Tech'), (5, 'Logistics'), (6, 'IOT'), (7, 'Food Tech'), (8, 'Renewable Energy')])),
                ('product_description', models.CharField(max_length=1000)),
                ('stage', models.IntegerField(choices=[(1, 'Pre-Seed'), (2, 'Seed'), (3, 'Series A'), (4, 'Series B'), (5, 'Series C')])),
                ('numbers_of_founders', models.IntegerField()),
                ('team_size', models.IntegerField()),
                ('investment_requirement', models.IntegerField()),
                ('monthly_revenue', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('linkedin', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('additional_documents', models.FileField(upload_to='document')),
            ],
        ),
    ]
