# Generated by Django 4.2.4 on 2024-02-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='member',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
