# Generated by Django 4.2.4 on 2024-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture_app', '0003_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='product_description',
            field=models.TextField(),
        ),
    ]
